/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package windows_new;

/**
 *
 * @author USER
 */
public class _fees extends javax.swing.JPanel {

    /**
     * Creates new form _home1
     */
    public _fees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jlblCourse1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_defaultTable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        lbl_seeName = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_seeProgYrBlk = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_newGrade = new javax.swing.JTextField();
        btn_updateRecord = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(1100, 630));
        setMinimumSize(new java.awt.Dimension(1100, 630));
        setPreferredSize(new java.awt.Dimension(1080, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("FEES");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 50));

        jlblCourse1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jlblCourse1.setForeground(new java.awt.Color(153, 153, 153));
        jlblCourse1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCourse1.setText("RFID-Based Kiosk System for Student Evaluation _ ACI Capstone for MIT 2024 _ JCA");
        jlblCourse1.setToolTipText("");
        add(jlblCourse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 380, 20));

        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Last Name", "First Name", "Suffix", "Middle Name", "Program/Year/Block", "Tuition", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setShowHorizontalLines(true);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1040, 170));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.setEditable(false);
        txt_search.setBackground(new java.awt.Color(255, 255, 255));
        txt_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_search.setText("Search student");
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        jPanel4.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 40));

        btn_search.setBackground(new java.awt.Color(0, 51, 102));
        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_search.setForeground(new java.awt.Color(255, 255, 255));
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sSMALLearch-icon-png-21.png"))); // NOI18N
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel4.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 40, 40));

        btn_defaultTable.setBackground(new java.awt.Color(0, 51, 102));
        btn_defaultTable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_defaultTable.setForeground(new java.awt.Color(255, 255, 255));
        btn_defaultTable.setText("All");
        btn_defaultTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_defaultTableActionPerformed(evt);
            }
        });
        jPanel4.add(btn_defaultTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 60, 40));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1040, 60));

        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DateTime", "Year Level", "Semester", "Payment", "Balance", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setShowHorizontalLines(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 640, 260));

        jLabel8.setText("Student Name");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 90, 20));

        lbl_seeName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbl_seeName.setText("-");
        lbl_seeName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lbl_seeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 360, 30));

        jLabel18.setText("Program/Year/Block");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 130, 20));

        lbl_seeProgYrBlk.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbl_seeProgYrBlk.setText("-");
        lbl_seeProgYrBlk.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lbl_seeProgYrBlk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 290, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("Payment");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 70, 20));

        txt_newGrade.setEditable(false);
        txt_newGrade.setBackground(new java.awt.Color(255, 255, 255));
        txt_newGrade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_newGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_newGradeActionPerformed(evt);
            }
        });
        add(txt_newGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 220, 40));

        btn_updateRecord.setBackground(new java.awt.Color(0, 51, 102));
        btn_updateRecord.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_updateRecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_updateRecord.setText("UPDATE RECORD");
        btn_updateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateRecordActionPerformed(evt);
            }
        });
        add(btn_updateRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_defaultTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_defaultTableActionPerformed
        
    }//GEN-LAST:event_btn_defaultTableActionPerformed

    private void txt_newGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_newGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_newGradeActionPerformed

    private void btn_updateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateRecordActionPerformed
       
        
    }//GEN-LAST:event_btn_updateRecordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_defaultTable;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_updateRecord;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jlblCourse1;
    private javax.swing.JLabel lbl_seeName;
    private javax.swing.JLabel lbl_seeProgYrBlk;
    private javax.swing.JTextField txt_newGrade;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
