/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package windows_new;

/**
 *
 * @author USER
 */
public class _home_faculty extends javax.swing.JPanel {

    /**
     * Creates new form _home1
     */
    public _home_faculty() {
        initComponents();
        
        jLabel1.setText("<html><body><p>The cashier account offers:</p><ul><li>Setting tuition</li><li>Recording student payments</li><li>Real-time kiosk record reflection</li></ul></body></html>");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblCourse1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlblCourse2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(1100, 630));
        setMinimumSize(new java.awt.Dimension(1100, 630));
        setPreferredSize(new java.awt.Dimension(1080, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblCourse1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jlblCourse1.setForeground(new java.awt.Color(153, 153, 153));
        jlblCourse1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCourse1.setText("RFID-Based Kiosk System for Student Evaluation _ ACI Capstone for MIT 2024 _ JCA");
        jlblCourse1.setToolTipText("");
        add(jlblCourse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 380, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 640, 270));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("DATA MANAGEMENT MODULE");
        jLabel11.setMaximumSize(new java.awt.Dimension(300, 30));
        jLabel11.setMinimumSize(new java.awt.Dimension(300, 30));
        jLabel11.setPreferredSize(new java.awt.Dimension(300, 30));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 510, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("RFID-BASED SYSTEM FOR STUDENT EVALUATION:");
        jLabel10.setMaximumSize(new java.awt.Dimension(300, 30));
        jLabel10.setMinimumSize(new java.awt.Dimension(300, 30));
        jLabel10.setPreferredSize(new java.awt.Dimension(300, 30));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 440, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("HOME : CASHIER");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 310, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(1100, 630));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblCourse2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jlblCourse2.setForeground(new java.awt.Color(153, 153, 153));
        jlblCourse2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCourse2.setText("RFID-Based Kiosk System for Student Evaluation _ ACI Capstone for MIT 2024 _ JCA");
        jlblCourse2.setToolTipText("");
        jPanel1.add(jlblCourse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 380, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("jLabel1");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 640, 270));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("DATA MANAGEMENT MODULE");
        jLabel12.setMaximumSize(new java.awt.Dimension(300, 30));
        jLabel12.setMinimumSize(new java.awt.Dimension(300, 30));
        jLabel12.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 510, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("RFID-BASED SYSTEM FOR STUDENT EVALUATION:");
        jLabel13.setMaximumSize(new java.awt.Dimension(300, 30));
        jLabel13.setMinimumSize(new java.awt.Dimension(300, 30));
        jLabel13.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 440, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("HOME : CASHIER");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 310, 60));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblCourse1;
    private javax.swing.JLabel jlblCourse2;
    // End of variables declaration//GEN-END:variables
}
