/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package windows_new;

/**
 *
 * @author USER
 */
public class _home_registrar extends javax.swing.JPanel {

    /**
     * Creates new form _home1
     */
    public _home_registrar() {
        initComponents();
        
        jLabel1.setText("<html><body><p>The registrar account offers:</p><ul><li>User enrollment</li><li>Resolving student alerts</li><li>Grade management</li><li>Database records management</li><li>Kiosk logs overview</li></ul></body></html>");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblCourse1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(1100, 630));
        setMinimumSize(new java.awt.Dimension(1100, 630));
        setPreferredSize(new java.awt.Dimension(1080, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblCourse1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jlblCourse1.setForeground(new java.awt.Color(153, 153, 153));
        jlblCourse1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCourse1.setText("RFID-Based Kiosk System for Student Evaluation _ ACI Capstone for MIT 2024 _ JCA");
        jlblCourse1.setToolTipText("");
        add(jlblCourse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 380, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("HOME : REGISTRAR");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 310, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("RFID-BASED SYSTEM FOR STUDENT EVALUATION:");
        jLabel10.setMaximumSize(new java.awt.Dimension(300, 30));
        jLabel10.setMinimumSize(new java.awt.Dimension(300, 30));
        jLabel10.setPreferredSize(new java.awt.Dimension(300, 30));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 440, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("DATA MANAGEMENT MODULE");
        jLabel11.setMaximumSize(new java.awt.Dimension(300, 30));
        jLabel11.setMinimumSize(new java.awt.Dimension(300, 30));
        jLabel11.setPreferredSize(new java.awt.Dimension(300, 30));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 510, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 640, 270));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlblCourse1;
    // End of variables declaration//GEN-END:variables
}
