/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows_new;

import windows_new.registrar.kioskAlert;

/**
 *
 * @author USER
 */
public class Window_Cashier extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Window_Cashier() {
        initComponents();
        btn_HOMEActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlblCourse2 = new javax.swing.JLabel();
        jlblCourse4 = new javax.swing.JLabel();
        jlblCourse5 = new javax.swing.JLabel();
        jlblCourse3 = new javax.swing.JLabel();
        jlblCourse6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        PANEL_1100by630 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_HOME = new javax.swing.JButton();
        btn_PAYMENT = new javax.swing.JButton();
        btn_LOGOUT = new javax.swing.JButton();
        btn_TUITION = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblCourse2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblCourse2.setForeground(new java.awt.Color(255, 204, 0));
        jlblCourse2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblCourse2.setText("SOUTHERN LUZON TECHNOLOGICAL COLLEGE FOUNDATION PILAR, INC.");
        jlblCourse2.setToolTipText("");
        jPanel2.add(jlblCourse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1020, 50));

        jlblCourse4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCourse4.setForeground(new java.awt.Color(255, 204, 0));
        jlblCourse4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCourse4.setText("RFID-BASED KIOSK SYSTEM");
        jlblCourse4.setToolTipText("");
        jPanel2.add(jlblCourse4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 10, 240, 40));

        jlblCourse5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCourse5.setForeground(new java.awt.Color(255, 204, 0));
        jlblCourse5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCourse5.setText("FOR STUDENT EVALUATION");
        jlblCourse5.setToolTipText("");
        jPanel2.add(jlblCourse5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 30, 240, 40));

        jlblCourse3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCourse3.setForeground(new java.awt.Color(255, 204, 0));
        jlblCourse3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCourse3.setText("(JCA, 2024)");
        jlblCourse3.setToolTipText("");
        jPanel2.add(jlblCourse3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 60, 240, 40));

        jlblCourse6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCourse6.setForeground(new java.awt.Color(255, 204, 0));
        jlblCourse6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblCourse6.setText("MARIFOSQUE, PILAR, SORSOGON");
        jlblCourse6.setToolTipText("");
        jPanel2.add(jlblCourse6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 540, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 80));

        jPanel9.setBackground(new java.awt.Color(255, 204, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1280, 10));

        PANEL_1100by630.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(PANEL_1100by630, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 1100, 630));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_HOME.setBackground(new java.awt.Color(255, 204, 0));
        btn_HOME.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_HOME.setForeground(new java.awt.Color(0, 0, 0));
        btn_HOME.setText("HOME");
        btn_HOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HOMEActionPerformed(evt);
            }
        });
        jPanel4.add(btn_HOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 40));

        btn_PAYMENT.setBackground(new java.awt.Color(255, 204, 0));
        btn_PAYMENT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_PAYMENT.setForeground(new java.awt.Color(0, 0, 0));
        btn_PAYMENT.setText("PAYMENT");
        btn_PAYMENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PAYMENTActionPerformed(evt);
            }
        });
        jPanel4.add(btn_PAYMENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 40));

        btn_LOGOUT.setBackground(new java.awt.Color(204, 0, 51));
        btn_LOGOUT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_LOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        btn_LOGOUT.setText("LOG OUT");
        btn_LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LOGOUTActionPerformed(evt);
            }
        });
        jPanel4.add(btn_LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 160, 40));

        btn_TUITION.setBackground(new java.awt.Color(255, 204, 0));
        btn_TUITION.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TUITION.setForeground(new java.awt.Color(0, 0, 0));
        btn_TUITION.setText("TUITION");
        btn_TUITION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TUITIONActionPerformed(evt);
            }
        });
        jPanel4.add(btn_TUITION, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HOMEActionPerformed
        enableButtons(); btn_HOME.setEnabled(false);
        PANEL_1100by630.removeAll();
        kioskAlert s = new kioskAlert();
        PANEL_1100by630.add(s);
        
        PANEL_1100by630.removeAll();
        _home_cashier h= new _home_cashier();
        PANEL_1100by630.add(h);
    }//GEN-LAST:event_btn_HOMEActionPerformed

    private void btn_LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LOGOUTActionPerformed
        int response = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to log out?", 
        "Confirm Logout", 
        javax.swing.JOptionPane.YES_NO_OPTION, 
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    
    if (response == javax.swing.JOptionPane.YES_OPTION) {
        
        Login w = new Login();
        w.setVisible(true);
        setVisible(false);
        dispose();
    }
    //  NO_OPTION is selected do nothing
    }//GEN-LAST:event_btn_LOGOUTActionPerformed

    private void btn_PAYMENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PAYMENTActionPerformed
        enableButtons(); btn_PAYMENT.setEnabled(false);
        PANEL_1100by630.removeAll();
        kioskAlert s = new kioskAlert();
        PANEL_1100by630.add(s);
        
        enableButtons(); btn_PAYMENT.setEnabled(false);
        PANEL_1100by630.removeAll();
        _fees_managePayment f = new _fees_managePayment();
        PANEL_1100by630.add(f);
    }//GEN-LAST:event_btn_PAYMENTActionPerformed

    private void btn_TUITIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TUITIONActionPerformed
        enableButtons(); btn_TUITION.setEnabled(false);
        PANEL_1100by630.removeAll();
        kioskAlert s = new kioskAlert();
        PANEL_1100by630.add(s);
        
        enableButtons(); btn_TUITION.setEnabled(false);
        PANEL_1100by630.removeAll();
        _fees_setTuition f = new _fees_setTuition();
        PANEL_1100by630.add(f);
    }//GEN-LAST:event_btn_TUITIONActionPerformed
    
    private void enableButtons(){
        btn_TUITION.setEnabled(true);
        btn_HOME.setEnabled(true);
        btn_PAYMENT.setEnabled(true);
    }
    
    private void home(){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_Cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANEL_1100by630;
    private javax.swing.JButton btn_HOME;
    private javax.swing.JButton btn_LOGOUT;
    private javax.swing.JButton btn_PAYMENT;
    private javax.swing.JButton btn_TUITION;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jlblCourse2;
    private javax.swing.JLabel jlblCourse3;
    private javax.swing.JLabel jlblCourse4;
    private javax.swing.JLabel jlblCourse5;
    private javax.swing.JLabel jlblCourse6;
    // End of variables declaration//GEN-END:variables
}
