/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows_new;

import windows_new.registrar.grades;
import windows_new.registrar.students;
import windows_new.registrar.kioskAlert;

/**
 *
 * @author USER
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Window() {
        initComponents();
//        btn_KIOSKALERTActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlblCourse2 = new javax.swing.JLabel();
        jlblCourse4 = new javax.swing.JLabel();
        jlblCourse5 = new javax.swing.JLabel();
        jlblCourse3 = new javax.swing.JLabel();
        jlblCourse6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        PANEL_1100by630 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_KIOSKALERT = new javax.swing.JButton();
        btn_STUDENTS = new javax.swing.JButton();
        btn_EVALUATION = new javax.swing.JButton();
        btn_GRADES = new javax.swing.JButton();
        btn_FEES = new javax.swing.JButton();
        btn_RECORDS = new javax.swing.JButton();
        btn_KIOSKLOGS = new javax.swing.JButton();
        btn_LOGOUT = new javax.swing.JButton();
        btn_KIOSKALERT1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblCourse2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblCourse2.setForeground(new java.awt.Color(255, 204, 0));
        jlblCourse2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblCourse2.setText("SOUTHERN LUZON TECHNOLOGICAL COLLEGE FOUNDATION PILAR, INC.");
        jlblCourse2.setToolTipText("");
        jPanel2.add(jlblCourse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1020, 50));

        jlblCourse4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCourse4.setForeground(new java.awt.Color(255, 204, 0));
        jlblCourse4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCourse4.setText("RFID-BASED KIOSK SYSTEM");
        jlblCourse4.setToolTipText("");
        jPanel2.add(jlblCourse4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 10, 240, 40));

        jlblCourse5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCourse5.setForeground(new java.awt.Color(255, 204, 0));
        jlblCourse5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCourse5.setText("FOR STUDENT EVALUATION");
        jlblCourse5.setToolTipText("");
        jPanel2.add(jlblCourse5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 30, 240, 40));

        jlblCourse3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCourse3.setForeground(new java.awt.Color(255, 204, 0));
        jlblCourse3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCourse3.setText("(JCA, 2024)");
        jlblCourse3.setToolTipText("");
        jPanel2.add(jlblCourse3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 60, 240, 40));

        jlblCourse6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCourse6.setForeground(new java.awt.Color(255, 204, 0));
        jlblCourse6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblCourse6.setText("MARIFOSQUE, PILAR, SORSOGON");
        jlblCourse6.setToolTipText("");
        jPanel2.add(jlblCourse6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 540, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 80));

        jPanel9.setBackground(new java.awt.Color(255, 204, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1280, 10));

        PANEL_1100by630.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(PANEL_1100by630, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 1100, 630));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_KIOSKALERT.setBackground(new java.awt.Color(255, 204, 0));
        btn_KIOSKALERT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_KIOSKALERT.setForeground(new java.awt.Color(0, 0, 0));
        btn_KIOSKALERT.setText("HOME");
        btn_KIOSKALERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KIOSKALERTActionPerformed(evt);
            }
        });
        jPanel4.add(btn_KIOSKALERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 40));

        btn_STUDENTS.setBackground(new java.awt.Color(255, 204, 0));
        btn_STUDENTS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_STUDENTS.setForeground(new java.awt.Color(0, 0, 0));
        btn_STUDENTS.setText("STUDENTS");
        btn_STUDENTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_STUDENTSActionPerformed(evt);
            }
        });
        jPanel4.add(btn_STUDENTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 40));

        btn_EVALUATION.setBackground(new java.awt.Color(255, 204, 0));
        btn_EVALUATION.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_EVALUATION.setForeground(new java.awt.Color(0, 0, 0));
        btn_EVALUATION.setText("EVALUATION");
        btn_EVALUATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EVALUATIONActionPerformed(evt);
            }
        });
        jPanel4.add(btn_EVALUATION, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 40));

        btn_GRADES.setBackground(new java.awt.Color(255, 204, 0));
        btn_GRADES.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_GRADES.setForeground(new java.awt.Color(0, 0, 0));
        btn_GRADES.setText("GRADES");
        btn_GRADES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GRADESActionPerformed(evt);
            }
        });
        jPanel4.add(btn_GRADES, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 40));

        btn_FEES.setBackground(new java.awt.Color(255, 204, 0));
        btn_FEES.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_FEES.setForeground(new java.awt.Color(0, 0, 0));
        btn_FEES.setText("FEES");
        btn_FEES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FEESActionPerformed(evt);
            }
        });
        jPanel4.add(btn_FEES, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, 40));

        btn_RECORDS.setBackground(new java.awt.Color(255, 204, 0));
        btn_RECORDS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_RECORDS.setForeground(new java.awt.Color(0, 0, 0));
        btn_RECORDS.setText("RECORDS");
        btn_RECORDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RECORDSActionPerformed(evt);
            }
        });
        jPanel4.add(btn_RECORDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 160, 40));

        btn_KIOSKLOGS.setBackground(new java.awt.Color(255, 204, 0));
        btn_KIOSKLOGS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_KIOSKLOGS.setForeground(new java.awt.Color(0, 0, 0));
        btn_KIOSKLOGS.setText("KIOSK LOGS");
        btn_KIOSKLOGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KIOSKLOGSActionPerformed(evt);
            }
        });
        jPanel4.add(btn_KIOSKLOGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 160, 40));

        btn_LOGOUT.setBackground(new java.awt.Color(204, 0, 51));
        btn_LOGOUT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_LOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        btn_LOGOUT.setText("LOG OUT");
        btn_LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LOGOUTActionPerformed(evt);
            }
        });
        jPanel4.add(btn_LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 160, 40));

        btn_KIOSKALERT1.setBackground(new java.awt.Color(255, 204, 0));
        btn_KIOSKALERT1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_KIOSKALERT1.setForeground(new java.awt.Color(0, 0, 0));
        btn_KIOSKALERT1.setText("KIOSK ALERTS");
        btn_KIOSKALERT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KIOSKALERT1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_KIOSKALERT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_KIOSKALERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KIOSKALERTActionPerformed
        enableButtons(); btn_KIOSKALERT.setEnabled(false);
        PANEL_1100by630.removeAll();
        kioskAlert s = new kioskAlert();
        PANEL_1100by630.add(s);
        
        PANEL_1100by630.removeAll();
        _home1 h= new _home1();
        PANEL_1100by630.add(h);
    }//GEN-LAST:event_btn_KIOSKALERTActionPerformed

    private void btn_EVALUATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EVALUATIONActionPerformed
         enableButtons(); btn_EVALUATION.setEnabled(false);
    }//GEN-LAST:event_btn_EVALUATIONActionPerformed

    private void btn_GRADESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GRADESActionPerformed
        enableButtons(); btn_GRADES.setEnabled(false);
        PANEL_1100by630.removeAll();
        grades s = new grades();
        PANEL_1100by630.add(s);
    }//GEN-LAST:event_btn_GRADESActionPerformed

    private void btn_FEESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FEESActionPerformed
         enableButtons(); btn_KIOSKALERT.setEnabled(false);
        PANEL_1100by630.removeAll();
        kioskAlert s = new kioskAlert();
        PANEL_1100by630.add(s);
        
        PANEL_1100by630.removeAll();
        _home1 h= new _home1();
        PANEL_1100by630.add(h);
        
        enableButtons(); btn_FEES.setEnabled(false);
        PANEL_1100by630.removeAll();
        _fees f = new _fees();
        PANEL_1100by630.add(f);
    }//GEN-LAST:event_btn_FEESActionPerformed

    private void btn_RECORDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RECORDSActionPerformed
         enableButtons(); btn_RECORDS.setEnabled(false);
    }//GEN-LAST:event_btn_RECORDSActionPerformed

    private void btn_KIOSKLOGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KIOSKLOGSActionPerformed
         enableButtons(); btn_KIOSKLOGS.setEnabled(false);
    }//GEN-LAST:event_btn_KIOSKLOGSActionPerformed

    private void btn_LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LOGOUTActionPerformed
        int response = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to log out?", 
        "Confirm Logout", 
        javax.swing.JOptionPane.YES_NO_OPTION, 
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    
    if (response == javax.swing.JOptionPane.YES_OPTION) {
        
        Login w = new Login();
        w.setVisible(true);
        setVisible(false);
        dispose();
    }
    //  NO_OPTION is selected do nothing
    }//GEN-LAST:event_btn_LOGOUTActionPerformed

    private void btn_STUDENTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_STUDENTSActionPerformed
         enableButtons(); btn_STUDENTS.setEnabled(false);
         PANEL_1100by630.removeAll();
        students s = new students();
        PANEL_1100by630.add(s);
    }//GEN-LAST:event_btn_STUDENTSActionPerformed

    private void btn_KIOSKALERT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KIOSKALERT1ActionPerformed
        enableButtons(); btn_KIOSKALERT1.setEnabled(false);
        PANEL_1100by630.removeAll();
        kioskAlert s = new kioskAlert();
        PANEL_1100by630.add(s);
    }//GEN-LAST:event_btn_KIOSKALERT1ActionPerformed
    
    private void enableButtons(){
        btn_EVALUATION.setEnabled(true);
        btn_FEES.setEnabled(true);
        btn_GRADES.setEnabled(true);
        btn_KIOSKALERT1.setEnabled(true);
        btn_KIOSKALERT.setEnabled(true);
        btn_KIOSKLOGS.setEnabled(true);
        btn_RECORDS.setEnabled(true);
        btn_STUDENTS.setEnabled(true);
    }
    
    private void home(){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANEL_1100by630;
    private javax.swing.JButton btn_EVALUATION;
    private javax.swing.JButton btn_FEES;
    private javax.swing.JButton btn_GRADES;
    private javax.swing.JButton btn_KIOSKALERT;
    private javax.swing.JButton btn_KIOSKALERT1;
    private javax.swing.JButton btn_KIOSKLOGS;
    private javax.swing.JButton btn_LOGOUT;
    private javax.swing.JButton btn_RECORDS;
    private javax.swing.JButton btn_STUDENTS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jlblCourse2;
    private javax.swing.JLabel jlblCourse3;
    private javax.swing.JLabel jlblCourse4;
    private javax.swing.JLabel jlblCourse5;
    private javax.swing.JLabel jlblCourse6;
    // End of variables declaration//GEN-END:variables
}
