/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package windows_new;

/**
 *
 * @author USER
 */
public class _home1 extends javax.swing.JPanel {

    /**
     * Creates new form _home1
     */
    public _home1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jlblCourse1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pan_About = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_About = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_kioskAlerts = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(1100, 630));
        setMinimumSize(new java.awt.Dimension(1100, 630));
        setPreferredSize(new java.awt.Dimension(1080, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("TITLE");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 310, 50));

        jlblCourse1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jlblCourse1.setForeground(new java.awt.Color(153, 153, 153));
        jlblCourse1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCourse1.setText("RFID-Based Kiosk System for Student Evaluation _ ACI Capstone for MIT 2024 _ JCA");
        jlblCourse1.setToolTipText("");
        add(jlblCourse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 380, 20));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_About.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pan_About.setMaximumSize(new java.awt.Dimension(300, 300));
        pan_About.setMinimumSize(new java.awt.Dimension(300, 300));
        pan_About.setPreferredSize(new java.awt.Dimension(300, 600));
        pan_About.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RFID-Based Kiosk System for ");
        jLabel3.setMaximumSize(new java.awt.Dimension(300, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(300, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(300, 30));
        pan_About.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Student Evaluation");
        jLabel7.setMaximumSize(new java.awt.Dimension(300, 30));
        jLabel7.setMinimumSize(new java.awt.Dimension(300, 30));
        jLabel7.setPreferredSize(new java.awt.Dimension(300, 30));
        pan_About.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 300, 30));

        lbl_About.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_About.setText("jLabel7");
        lbl_About.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pan_About.add(lbl_About, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, 450));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DATA MANAGEMENT MODULE");
        jLabel8.setMaximumSize(new java.awt.Dimension(300, 30));
        jLabel8.setMinimumSize(new java.awt.Dimension(300, 30));
        jLabel8.setPreferredSize(new java.awt.Dimension(300, 30));
        pan_About.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 30));

        jPanel4.add(pan_About, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 590));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 320, 630));

        btn_kioskAlerts.setBackground(new java.awt.Color(255, 204, 0));
        btn_kioskAlerts.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_kioskAlerts.setForeground(new java.awt.Color(0, 0, 0));
        btn_kioskAlerts.setText("KIOSK ALERTS");
        btn_kioskAlerts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kioskAlertsActionPerformed(evt);
            }
        });
        add(btn_kioskAlerts, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 350, 80));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("HOME");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 310, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kioskAlertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kioskAlertsActionPerformed
        
    }//GEN-LAST:event_btn_kioskAlertsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kioskAlerts;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlblCourse1;
    private javax.swing.JLabel lbl_About;
    private javax.swing.JPanel pan_About;
    // End of variables declaration//GEN-END:variables
}
